runtime: python311
# https://github.com/GoogleCloudPlatform/appengine-python-standard
app_engine_apis: true

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto


inbound_services:
- mail
- mail_bounce


env_variables:
  DEFERRED_USE_CROSS_COMPATIBLE_PICKLE_PROTOCOL: 'True'
  MEMCACHE_USE_CROSS_COMPATIBLE_PROTOCOL: 'True'
  NDB_USE_CROSS_COMPATIBLE_PICKLE_PROTOCOL: 'True'
#  REDISHOST: '10.220.95.155'
#  REDISPORT: '6379'
#  REDIS_CACHE_URL: 'redis://10.220.95.155:6379'

# subnet :10.220.95.144/28
#vpc_access_connector:
#  name: projects/skojjt-3/locations/europe-west1/connectors/redis-connector-skojjt
